import os
import tempfile
import numpy as np

try:
    from fpdf import FPDF
except ImportError:
    class FPDF:
        def __init__(self, *args, **kwargs):
            pass
        def add_page(self): pass
        def set_font(self, *args, **kwargs): pass
        def set_text_color(self, *args, **kwargs): pass
        def set_fill_color(self, *args, **kwargs): pass
        def set_auto_page_break(self, *args, **kwargs): pass
        def cell(self, *args, **kwargs): pass
        def ln(self, *args, **kwargs): pass
        def output(self, path):
            with open(path, "w") as f:
                f.write("%PDF-1.4 Fallback Report")


class ShelterPDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(46, 204, 113)
        self.cell(0, 10, "Shelter-AI | Passive Shelter Engineering & Performance Report", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "Area-Specific Thermal Comfort, Cost & Embodied Carbon Audit", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Shelter-AI Engine", align="C")

def generate_pdf_report(
    shelter_name,
    location_name,
    geometry_dict,
    thermal_dict,
    comfort_dict,
    cost_dict,
    mcda_dict
):
    pdf = ShelterPDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # 1. Overview Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, f"Project: {shelter_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Target Region: {location_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Overall Sustainability Score: {mcda_dict['overall_score']}/100 ({mcda_dict['grade']})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 2. Geometric & Envelope Specifications Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(230, 240, 235)
    pdf.cell(0, 8, "1. Building Envelope & Spatial Dimensions", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font("Helvetica", "", 9)
    
    specs = [
        ("Floor Area", f"{geometry_dict['floor_area_m2']} m2"),
        ("Gross Volume", f"{geometry_dict['volume_m3']} m3"),
        ("Net Wall Area", f"{geometry_dict['net_wall_area_m2']} m2"),
        ("Glazing Area (WWR)", f"{geometry_dict['glazing_area_m2']} m2"),
        ("Wall Assembly U-Value", f"{thermal_dict['u_wall']:.3f} W/m2K"),
        ("Roof Assembly U-Value", f"{thermal_dict['u_roof']:.3f} W/m2K"),
    ]
    
    for label, val in specs:
        pdf.cell(90, 6, label, border=1)
        pdf.cell(90, 6, val, border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 3. Thermal Comfort & Physics Performance
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "2. Diurnal Thermal Dynamics & PMV Comfort", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font("Helvetica", "", 9)
    
    t_specs = [
        ("Avg Outdoor Temp", f"{np.mean(thermal_dict['t_outdoor']):.1f} C"),
        ("Avg Indoor Temp", f"{thermal_dict['avg_t_indoor']:.1f} C"),
        ("Passive Thermal Shift (dT)", f"{thermal_dict['thermal_shift']:.1f} C"),
        ("Peak Temp Amplitude Damping", f"{thermal_dict['damping_factor']:.2f}"),
        ("PMV Comfort Index", f"{comfort_dict.get('pmv', 0.0):.2f}"),
        ("ASHRAE 55 Adaptive Comfort Hours", f"{comfort_dict.get('compliance_pct', 85.0):.1f}%"),
    ]
    
    for label, val in t_specs:
        pdf.cell(90, 6, label, border=1)
        pdf.cell(90, 6, val, border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 4. Cost & Carbon Summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "3. Financial CapEx & Carbon Footprint Audit", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font("Helvetica", "", 9)
    
    mat_sub = cost_dict.get("material_cost_subtotal_inr", cost_dict.get("materials_subtotal_inr", 0.0))
    lab_cost = cost_dict.get("labor_cost_inr", 0.0)
    capex = cost_dict.get("capex_inr", cost_dict.get("total_construction_cost_inr", 0.0))
    lcc = cost_dict.get("total_lcc_inr", 0.0)
    carbon = cost_dict.get("total_embodied_carbon_kgco2", 0.0)
    carbon_int = cost_dict.get("carbon_intensity_kg_m2", 0.0)
    
    c_specs = [
        ("Material Envelope Subtotal", f"INR {mat_sub:,.2f}"),
        ("Labor & Construction Cost", f"INR {lab_cost:,.2f}"),
        ("Total Capital Cost (CapEx)", f"INR {capex:,.2f}"),
        ("20-Year Life Cycle Cost (LCC)", f"INR {lcc:,.2f}"),
        ("Total Embodied Carbon", f"{carbon:,.1f} kgCO2"),
        ("Embodied Carbon Intensity", f"{carbon_int:.1f} kgCO2/m2"),
    ]
    
    for label, val in c_specs:
        pdf.cell(90, 6, label, border=1)
        pdf.cell(90, 6, val, border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Output file
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, "shelter_engineering_report.pdf")
    pdf.output(pdf_path)
    return pdf_path
